### ISSUE TITLE
请问如何使用？

### ISSUE THREAD

**Issue by 1834423612** [Frost-ZX/dynmap-export-js#1]
是直接浏览器控制台执行还是需要node之类的运行
谢谢大佬

**Comment by Frost-ZX** [comment]
访问网页地图页面，然后在浏览器的开发人员工具的控制台或“Sources -> Snippets”里执行。

目前有两个模式，通过 `mode` 参数指定，均为导出已浏览过的区域（即执行代码前需要通过手动拖动让浏览器加载地图）。`corner` 模式会根据浏览过的区域计算出矩形范围进行导出，而 `viewed` 模式则只导出加载过的地图区域。

示例调用方式：

```javascript
exportDynmap({
  dynmap: window.dynmap, // 指定网页地图页面对外暴露的 dynmap 对象
  autoStart: false,      // 是否自动开始（不需要执行函数进行确认）
  calcOnly: false,       // 是否只输出导出范围信息
  fillColor: '#FFFFFF',  // 图片空白区域的颜色
  maxTiles: null,        // 最多可以请求的地图图片数量，超出则停止并返回结果
  mode: 'corner',        // 指定导出模式
  timeout: 20,           // 确认导出前的等待秒数，超时则取消导出
});
```

**Comment by 1834423612** [comment]
谢谢谢谢，非常感谢🥰😉











---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月12日(周日) 上午6:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Frost-ZX/dynmap-export-js] 请问如何使用？ (Issue #1)




 
访问网页地图页面，然后在浏览器的开发人员工具的控制台或“Sources -&gt; Snippets”里执行。
 
目前有两个模式，通过 mode 参数指定，均为导出已浏览过的区域（即执行代码前需要通过手动拖动让浏览器加载地图）。corner 模式会根据浏览过的区域计算出矩形范围进行导出，而 viewed 模式则只导出加载过的地图区域。
 
示例调用方式：
 exportDynmap({   dynmap: window.dynmap, // 指定网页地图页面对外暴露的 dynmap 对象   autoStart: false,      // 是否自动开始（不需要执行函数进行确认）   calcOnly: false,       // 是否只输出导出范围信息   fillColor: '#FFFFFF',  // 图片空白区域的颜色   maxTiles: null,        // 最多可以请求的地图图片数量，超出则停止并返回结果   mode: 'corner',        // 指定导出模式   timeout: 20,           // 确认导出前的等待秒数，超时则取消导出 });
